Provide more detailed messages when failing to spawn processes
Before:

```
Error: Could not initialize server

Caused by:
    0: Could not initialize server
    1: Could not initialize listener collection
    2: No such file or directory (os error 2)
```

After:

```
Error: Could not initialize server

Caused by:
    0: Could not initialize server
    1: Could not initialize listener collection
    2: Could not spawn /home/dev-sable/.cargo/bin/listener_process: No such file or directory (os error 2)
```